[auth]
redirect_uri = "" # Adjust for deployment
domain = "[your domain]"
client_id = "[your client id]"
client_secret = "[your client secret]"
server_metadata_url = "https://[your domain]/.well-known/openid-configuration"
cookie_secret = "[your cookie secret]"